COMMON_FLAGS="-O3 -pipe -march=znver5 -fomit-frame-pointer -flto=auto -fno-semantic-interposition -Wno-error=incompatible-pointer-types-discards-qualifiers"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
FEATURES="ccache candy sandbox parallel-fetch parallel-install binpkg-request-signature userfetch"
EMERGE_DEFAULT_OPTS="--tree --verbose --keep-going=y --load-average=28.0 -j1"
PORTAGE_SCHEDULING_POLICY="idle"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=znver5"
LDFLAGS="-fuse-ld=mold -Wl,-O3 -Wl,--as-needed -flto=auto"


CC="clang"
CPP="clang-cpp"
CXX="clang++"
AS="clang -c"
AR="llvm-ar"
NM="llvm-nm"
STRIP="llvm-strip"
RANLIB="llvm-ranlib"
OBJCOPY="llvm-objcopy"
STRINGS="llvm-strings"
OBJDUMP="llvm-objdump"
READELF="llvm-readelf"
ADDR2LINE="llvm-addr2linei"



VIDEO_CARDS="amdgpu radeonsi zink"

INPUT_DEVICE="libinput"


MAKEOPT="-j28 -l28"

USE="-gnome -dvd -branding -cups -css -systemd -kde -wifi -gtk -gtk2 -gtk3 -gtk4 -qt5 qt6 -bluetooth wayland xwayland clang opus -xemacs -emacs zstd flac lto -X elogind vulkan opengl opencl alsa acl pipewire pulseaudio vaapi x264 openh265 system-av1 system-pipewire strip flatpak bpf privsep -suid -xorg minimal -telemetry -debug udev -docs dbus"

CPU_FLAGS_X86="aes avx avx2 avx512_bf16 avx512_bitalg avx512_vbmi2 avx512_vnni avx512_vp2intersect avx512_vpopcntdq avx512bw avx512cd avx512dq avx512f avx512ifma avx512vbmi avx512vl avx_vnni bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"

LC_MESSAGES=C.UTF-8
GTUB_PLATFORMS="efi-64"

POLICY_TYPES="mcs"
