hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("wbg /home/fcc/walls/wall.png")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/usr/libexec/xdg-desktop-portal -r")
    hl.exec_cmd("/usr/libexec/xdg-desktop-portal-gtk -r")
    hl.exec_cmd("/usr/libexec/xdg-desktop-portal-hyprland")
    hl.exec_cmd("nohup gentoo-pipewire-launcher restart > /dev/null 2>&1")
    hl.exec_cmd("keepassxc")
end)
