(setq straight-use-package-by-default t)
(setq warning-suppress-log-types '((native-compiler)))
(setq org-persist-remote-files nil)
(setq org-persist-directory (expand-file-name "org-persist/" user-emacs-directory))
(setq x-meta-keysym 'alt)
(setq x-alt-keysym 'meta)
(setq gc-cons-threshold 100000000)
(setq inhibit-startup-screen t)
(setq-default c-basic-offset 4)
(setq-default python-indent-offset 4)
(setq-default rust-indent-offset 4)
(setq-default lua-indent-level 4)
(setq electric-indent-mode t)
(setq initial-buffer-choice 'dashboard-open)

(provide 'core)
