general {
    lock_cmd = pidof waylock || waylock
    after_sleep_cmd = hyprctl dispatch dpms on
    before_suspend_cmd = pidof swaylock || swaylock
    after_resume_cmd = hyprctl dispatch dpms on

    on_unlock_cmd = pkill -SIGUSR1 waybar || waybar
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    event = "suspend"
    on-event = pidof swaylock || swaylock
    on-resume = hyprctl dispatch dpms on
}